var names_de = [{"id":"Adak","name":"Adak","wikipedia":"Adak,_Alaska"},
{"id":"Nukuʻalofa","name":"Nukuʻalofa","wikipedia":"Nukuʻalofa"},
{"id":"Apia","name":"Apia","wikipedia":"Apia"},
{"id":"Pago Pago","name":"Pago Pago","wikipedia":"Pago_Pago"},
{"id":"Alofi","name":"Alofi","wikipedia":"Alofi"},
{"id":"Avarua","name":"Avarua","wikipedia":"Avarua"},
{"id":"Honolulu","name":"Honolulu","wikipedia":"Honolulu"},
{"id":"Hilo","name":"Hilo","wikipedia":"Hilo,_Hawaii"},
{"id":"Anchorage","name":"Anchorage","wikipedia":"Anchorage,_Alaska"},
{"id":"Papeete","name":"Papeete","wikipedia":"Papeete"},
{"id":"Fairbanks","name":"Fairbanks","wikipedia":"Fairbanks,_Alaska"},
{"id":"Sitka","name":"Sitka","wikipedia":"Sitka,_Alaska"},
{"id":"Whitehorse","name":"Whitehorse","wikipedia":"Whitehorse,_Yukon"},
{"id":"Juneau","name":"Juneau","wikipedia":"Juneau,_Alaska"},
{"id":"Adamstown","name":"Adamstown","wikipedia":"Adamstown,_Pitcairn_Islands"},
{"id":"Vancouver","name":"Vancouver","wikipedia":"Vancouver"},
{"id":"Rabi Island","name":"Rabi Island","wikipedia":"Rabi_Island"},
{"id":"Portland","name":"Portland","wikipedia":"Portland,_Oregon"},
{"id":"San Francisco","name":"San Francisco","wikipedia":"San_Francisco"},
{"id":"Seattle","name":"Seattle","wikipedia":"Seattle"},
{"id":"Sacramento","name":"Sacramento","wikipedia":"Sacramento,_California"},
{"id":"Los Angeles","name":"Los Angeles","wikipedia":"Los_Angeles"},
{"id":"Riverside","name":"Riverside","wikipedia":"Riverside,_California"},
{"id":"San Diego","name":"San Diego","wikipedia":"San_Diego"},
{"id":"Tijuana","name":"Tijuana","wikipedia":"Tijuana"},
{"id":"Mexicali","name":"Mexicali","wikipedia":"Mexicali"},
{"id":"Las Vegas","name":"Las Vegas","wikipedia":"Las_Vegas,_Nevada"},
{"id":"Yellowknife","name":"Yellowknife","wikipedia":"Yellowknife"},
{"id":"Calgary","name":"Calgary","wikipedia":"Calgary"},
{"id":"Edmonton","name":"Edmonton","wikipedia":"Edmonton"},
{"id":"Phoenix","name":"Phoenix","wikipedia":"Phoenix,_Arizona"},
{"id":"Salt Lake City","name":"Salt Lake City","wikipedia":"Salt_Lake_City"},
{"id":"Tucson","name":"Tucson","wikipedia":"Tucson,_Arizona"},
{"id":"Hanga Roa","name":"Hanga Roa","wikipedia":"Hanga_Roa"},
{"id":"Saskatoon","name":"Saskatoon","wikipedia":"Saskatoon"},
{"id":"Albuquerque","name":"Albuquerque","wikipedia":"Albuquerque,_New_Mexico"},
{"id":"El Paso","name":"El Paso","wikipedia":"El_Paso,_Texas"},
{"id":"Chihuahua","name":"Chihuahua","wikipedia":"Chihuahua,_Chihuahua"},
{"id":"Denver","name":"Denver","wikipedia":"Denver"},
{"id":"Durango","name":"Durango","wikipedia":"Durango,_Durango"},
{"id":"Regina","name":"Regina","wikipedia":"Regina,_Saskatchewan"},
{"id":"Zapopan","name":"Zapopan","wikipedia":"Zapopan,_Jalisco"},
{"id":"Guadalajara","name":"Guadalajara","wikipedia":"Guadalajara,_Jalisco"},
{"id":"Monterrey","name":"Monterrey","wikipedia":"Monterrey"},
{"id":"Mexico City","name":"Mexico City","wikipedia":"Mexico_City"},
{"id":"San Antonio","name":"San Antonio","wikipedia":"San_Antonio"},
{"id":"Puebla","name":"Puebla","wikipedia":"Puebla,_Puebla"},
{"id":"Austin","name":"Austin","wikipedia":"Austin,_Texas"},
{"id":"Oklahoma City","name":"Oklahoma City","wikipedia":"Oklahoma_City"},
{"id":"Wichita","name":"Wichita","wikipedia":"Wichita,_Kansas"},
{"id":"Winnipeg","name":"Winnipeg","wikipedia":"Winnipeg"},
{"id":"Dallas","name":"Dallas","wikipedia":"Dallas"},
{"id":"Veracruz","name":"Veracruz","wikipedia":"Veracruz,_Veracruz"},
{"id":"Houston","name":"Houston","wikipedia":"Houston"},
{"id":"Kansas City","name":"Kansas City","wikipedia":"Kansas_City,_Missouri"},
{"id":"Minneapolis","name":"Minneapolis","wikipedia":"Minneapolis"},
{"id":"Quetzaltenango","name":"Quetzaltenango","wikipedia":"Quetzaltenango"},
{"id":"Guatemala City","name":"Guatemala City","wikipedia":"Guatemala_City"},
{"id":"St. Louis","name":"St. Louis","wikipedia":"St._Louis,_Missouri"},
{"id":"New Orleans","name":"New Orleans","wikipedia":"New_Orleans"},
{"id":"Memphis","name":"Memphis","wikipedia":"Memphis,_Tennessee"},
{"id":"Mérida","name":"Mérida","wikipedia":"Mérida,_Yucatán"},
{"id":"San Salvador","name":"San Salvador","wikipedia":"San_Salvador"},
{"id":"Belmopan","name":"Belmopan","wikipedia":"Belmopan"},
{"id":"Belize City","name":"Belize City","wikipedia":"Belize_City"},
{"id":"Milwaukee","name":"Milwaukee","wikipedia":"Milwaukee"},
{"id":"Chicago","name":"Chicago","wikipedia":"Chicago"},
{"id":"Tegucigalpa","name":"Tegucigalpa","wikipedia":"Tegucigalpa"},
{"id":"Nashville","name":"Nashville","wikipedia":"Nashville,_Tennessee"},
{"id":"Managua","name":"Managua","wikipedia":"Managua"},
{"id":"Indianapolis","name":"Indianapolis","wikipedia":"Indianapolis"},
{"id":"Louisville","name":"Louisville","wikipedia":"Louisville,_Kentucky"},
{"id":"Cincinnati","name":"Cincinnati","wikipedia":"Cincinnati"},
{"id":"Atlanta","name":"Atlanta","wikipedia":"Atlanta"},
{"id":"San José","name":"San José","wikipedia":"San_José,_Costa_Rica"},
{"id":"Detroit","name":"Detroit","wikipedia":"Detroit"},
{"id":"Columbus","name":"Columbus","wikipedia":"Columbus,_Ohio"},
{"id":"Tampa","name":"Tampa","wikipedia":"Tampa,_Florida"},
{"id":"Havana","name":"Havana","wikipedia":"Havana"},
{"id":"Cleveland","name":"Cleveland","wikipedia":"Cleveland"},
{"id":"Jacksonville","name":"Jacksonville","wikipedia":"Jacksonville,_Florida"},
{"id":"George Town","name":"George Town","wikipedia":"George_Town,_Penang"},
{"id":"Charlotte","name":"Charlotte","wikipedia":"Charlotte,_North_Carolina"},
{"id":"Miami","name":"Miami","wikipedia":"Miami"},
{"id":"Pittsburgh","name":"Pittsburgh","wikipedia":"Pittsburgh"},
{"id":"Guayaquil","name":"Guayaquil","wikipedia":"Guayaquil"},
{"id":"Panama City","name":"Panama City","wikipedia":"Panama_City"},
{"id":"Toronto","name":"Toronto","wikipedia":"Toronto"},
{"id":"Buffalo","name":"Buffalo","wikipedia":"Buffalo,_New_York"},
{"id":"Raleigh","name":"Raleigh","wikipedia":"Raleigh,_North_Carolina"},
{"id":"Quito","name":"Quito","wikipedia":"Quito"},
{"id":"Rochester","name":"Rochester","wikipedia":"Rochester,_New_York"},
{"id":"Nassau","name":"Nassau","wikipedia":"Nassau,_Bahamas"},
{"id":"Washington","name":"Washington","wikipedia":"Washington,_D.C."},
{"id":"Lima","name":"Lima","wikipedia":"Lima"},
{"id":"Kingston","name":"Kingston","wikipedia":"Kingston,_Norfolk_Island"},
{"id":"Baltimore","name":"Baltimore","wikipedia":"Baltimore"},
{"id":"Cali","name":"Cali","wikipedia":"Cali"},
{"id":"Virginia Beach","name":"Virginia Beach","wikipedia":"Virginia_Beach"},
{"id":"Santiago de Cuba","name":"Santiago de Cuba","wikipedia":"Santiago_de_Cuba"},
{"id":"Ottawa","name":"Ottawa","wikipedia":"Ottawa"},
{"id":"Medellín","name":"Medellín","wikipedia":"Medellín"},
{"id":"Cartagena","name":"Cartagena","wikipedia":"Cartagena,_Colombia"},
{"id":"Philadelphia","name":"Philadelphia","wikipedia":"Philadelphia"},
{"id":"Barranquilla","name":"Barranquilla","wikipedia":"Barranquilla"},
{"id":"Forked River","name":"Forked River","wikipedia":"Forked_River"},
{"id":"Jersey City","name":"Jersey City","wikipedia":"Jersey_City,_New_Jersey"},
{"id":"Bogotá","name":"Bogotá","wikipedia":"Bogotá"},
{"id":"New York City","name":"New York City","wikipedia":"New_York_City"},
{"id":"Montreal","name":"Montreal","wikipedia":"Montreal"},
{"id":"Iquitos","name":"Iquitos","wikipedia":"Iquitos"},
{"id":"Valdivia","name":"Valdivia","wikipedia":"Valdivia,_Chile"},
{"id":"Concepción","name":"Concepción","wikipedia":"Concepción,_Chile"},
{"id":"Port-au-Prince","name":"Port-au-Prince","wikipedia":"Port-au-Prince"},
{"id":"Cusco","name":"Cusco","wikipedia":"Cusco"},
{"id":"Maracaibo","name":"Maracaibo","wikipedia":"Maracaibo"},
{"id":"Valparaíso","name":"Valparaíso","wikipedia":"Valparaíso"},
{"id":"Arequipa","name":"Arequipa","wikipedia":"Arequipa"},
{"id":"Providence","name":"Providence","wikipedia":"Providence,_Rhode_Island"},
{"id":"San Carlos de Bariloche","name":"San Carlos de Bariloche","wikipedia":"San_Carlos_de_Bariloche"},
{"id":"La Serena","name":"La Serena","wikipedia":"La_Serena,_Chile"},
{"id":"Quebec City","name":"Quebec City","wikipedia":"Quebec_City"},
{"id":"Cockburn Town","name":"Cockburn Town","wikipedia":"Cockburn_Town"},
{"id":"Boston","name":"Boston","wikipedia":"Boston"},
{"id":"Punta Arenas","name":"Punta Arenas","wikipedia":"Punta_Arenas,_Chile"},
{"id":"Santiago","name":"Santiago","wikipedia":"Santiago,_Chile"},
{"id":"Antofagasta","name":"Antofagasta","wikipedia":"Antofagasta"},
{"id":"Iquique","name":"Iquique","wikipedia":"Iquique"},
{"id":"Oranjestad","name":"Oranjestad","wikipedia":"Oranjestad,_Aruba"},
{"id":"Santo Domingo","name":"Santo Domingo","wikipedia":"Santo_Domingo"},
{"id":"Rio Branco","name":"Rio Branco","wikipedia":"Rio_Branco"},
{"id":"Willemstad","name":"Willemstad","wikipedia":"Willemstad"},
{"id":"Calama","name":"Calama","wikipedia":"Calama,_Chile"},
{"id":"Mendoza","name":"Mendoza","wikipedia":"Mendoza,_Argentina"},
{"id":"Iqaluit","name":"Iqaluit","wikipedia":"Iqaluit"},
{"id":"Ushuaia","name":"Ushuaia","wikipedia":"Ushuaia"},
{"id":"La Paz","name":"La Paz","wikipedia":"La_Paz"},
{"id":"Puerto Williams","name":"Puerto Williams","wikipedia":"Puerto_Williams"},
{"id":"Caracas","name":"Caracas","wikipedia":"Caracas"},
{"id":"Fredericton","name":"Fredericton","wikipedia":"Fredericton"},
{"id":"San Juan","name":"San Juan","wikipedia":"San_Juan,_Puerto_Rico"},
{"id":"Saint John","name":"Saint John","wikipedia":"Saint_John,_New_Brunswick"},
{"id":"Sucre","name":"Sucre","wikipedia":"Sucre"},
{"id":"Charlotte Amalie","name":"Charlotte Amalie","wikipedia":"Charlotte_Amalie,_United_States_Virgin_Islands"},
{"id":"Hamilton","name":"Hamilton","wikipedia":"Hamilton,_New_Zealand"},
{"id":"Road Town","name":"Road Town","wikipedia":"Road_Town"},
{"id":"Córdoba","name":"Córdoba","wikipedia":"Córdoba,_Argentina"},
{"id":"Porto Velho","name":"Porto Velho","wikipedia":"Porto_Velho"},
{"id":"City of Halifax","name":"City of Halifax","wikipedia":"City_of_Halifax"},
{"id":"Santa Cruz de la Sierra","name":"Santa Cruz de la Sierra","wikipedia":"Santa_Cruz_de_la_Sierra"},
{"id":"Charlottetown","name":"Charlottetown","wikipedia":"Charlottetown"},
{"id":"The Valley","name":"The Valley","wikipedia":"The_Valley,_Anguilla"},
{"id":"Basse-Terre","name":"Basse-Terre","wikipedia":"Basse-Terre"},
{"id":"Bahía Blanca","name":"Bahía Blanca","wikipedia":"Bahía_Blanca"},
{"id":"St. John's","name":"St. John's","wikipedia":"St._John's,_Newfoundland_and_Labrador"},
{"id":"St. George's","name":"St. George's","wikipedia":"St._George's,_Grenada"},
{"id":"Port of Spain","name":"Port of Spain","wikipedia":"Port_of_Spain"},
{"id":"San Fernando","name":"San Fernando","wikipedia":"San_Fernando,_Trinidad_and_Tobago"},
{"id":"Roseau","name":"Roseau","wikipedia":"Roseau"},
{"id":"Chaguanas","name":"Chaguanas","wikipedia":"Chaguanas"},
{"id":"Kingstown","name":"Kingstown","wikipedia":"Kingstown"},
{"id":"Fort-de-France","name":"Fort-de-France","wikipedia":"Fort-de-France"},
{"id":"Castries","name":"Castries","wikipedia":"Castries"},
{"id":"Rosario","name":"Rosario","wikipedia":"Rosario,_Santa_Fe"},
{"id":"Boa Vista","name":"Boa Vista","wikipedia":"Boa_Vista,_Roraima"},
{"id":"Manaus","name":"Manaus","wikipedia":"Manaus"},
{"id":"Bridgetown","name":"Bridgetown","wikipedia":"Bridgetown"},
{"id":"Buenos Aires","name":"Buenos Aires","wikipedia":"Buenos_Aires"},
{"id":"Stanley","name":"Stanley","wikipedia":"Stanley,_Falkland_Islands"},
{"id":"Asunción","name":"Asunción","wikipedia":"Asunción"},
{"id":"Saint-Pierre","name":"Saint-Pierre","wikipedia":"Saint-Pierre,_Saint_Pierre_and_Miquelon"},
{"id":"Montevideo","name":"Montevideo","wikipedia":"Montevideo"},
{"id":"Cuiabá","name":"Cuiabá","wikipedia":"Cuiabá"},
{"id":"Paramaribo","name":"Paramaribo","wikipedia":"Paramaribo"},
{"id":"Campo Grande","name":"Campo Grande","wikipedia":"Campo_Grande"},
{"id":"Ciudad del Este","name":"Ciudad del Este","wikipedia":"Ciudad_del_Este"},
{"id":"Chuí","name":"Chuí","wikipedia":"Chuí"},
{"id":"Pelotas","name":"Pelotas","wikipedia":"Pelotas"},
{"id":"Cayenne","name":"Cayenne","wikipedia":"Cayenne"},
{"id":"Nuuk","name":"Nuuk","wikipedia":"Nuuk"},
{"id":"Porto Alegre","name":"Porto Alegre","wikipedia":"Porto_Alegre"},
{"id":"Macapá","name":"Macapá","wikipedia":"Macapá"},
{"id":"Assis","name":"Assis","wikipedia":"Assis"},
{"id":"Curitiba","name":"Curitiba","wikipedia":"Curitiba"},
{"id":"Belém","name":"Belém","wikipedia":"Belém"},
{"id":"Brasília","name":"Brasília","wikipedia":"Brasília"},
{"id":"Campinas","name":"Campinas","wikipedia":"Campinas"},
{"id":"São Paulo","name":"São Paulo","wikipedia":"São_Paulo"},
{"id":"São José dos Campos","name":"São José dos Campos","wikipedia":"São_José_dos_Campos"},
{"id":"Rio de Janeiro","name":"Rio de Janeiro","wikipedia":"Rio_de_Janeiro"},
{"id":"Vitória","name":"Vitória","wikipedia":"Vitória,_Brazil"},
{"id":"Ilhéus","name":"Ilhéus","wikipedia":"Ilhéus"},
{"id":"Fortaleza","name":"Fortaleza","wikipedia":"Fortaleza"},
{"id":"Maceió","name":"Maceió","wikipedia":"Maceió"},
{"id":"Recife","name":"Recife","wikipedia":"Recife"},
{"id":"Horta (Azores)","name":"Horta (Azores)","wikipedia":"Horta_(Azores)"},
{"id":"Angra do Heroísmo","name":"Angra do Heroísmo","wikipedia":"Angra_do_Heroísmo"},
{"id":"Ponta Delgada","name":"Ponta Delgada","wikipedia":"Ponta_Delgada,_São_Miguel_Island"},
{"id":"Praia","name":"Praia","wikipedia":"Praia"},
{"id":"Reykjavík","name":"Reykjavík","wikipedia":"Reykjavík"},
{"id":"Dakar","name":"Dakar","wikipedia":"Dakar"},
{"id":"Thiès","name":"Thiès","wikipedia":"Thiès"},
{"id":"Serekunda","name":"Serekunda","wikipedia":"Serekunda"},
{"id":"Brikama","name":"Brikama","wikipedia":"Brikama"},
{"id":"Banjul","name":"Banjul","wikipedia":"Banjul"},
{"id":"Santa Cruz de Tenerife","name":"Santa Cruz de Tenerife","wikipedia":"Santa_Cruz_de_Tenerife"},
{"id":"Nouakchott","name":"Nouakchott","wikipedia":"Nouakchott"},
{"id":"Bissau","name":"Bissau","wikipedia":"Bissau"},
{"id":"Las Palmas de Gran Canaria","name":"Las Palmas de Gran Canaria","wikipedia":"Las_Palmas_de_Gran_Canaria"},
{"id":"Conakry","name":"Conakry","wikipedia":"Conakry"},
{"id":"Freetown","name":"Freetown","wikipedia":"Freetown"},
{"id":"El Aaiún","name":"El Aaiún","wikipedia":"El_Aaiún"},
{"id":"Monrovia","name":"Monrovia","wikipedia":"Monrovia"},
{"id":"Lisbon","name":"Lisbon","wikipedia":"Lisbon"},
{"id":"Porto","name":"Porto","wikipedia":"Porto"},
{"id":"Cork (city)","name":"Cork (city)","wikipedia":"Cork_(city)"},
{"id":"Marrakech","name":"Marrakech","wikipedia":"Marrakech"},
{"id":"Bamako","name":"Bamako","wikipedia":"Bamako"},
{"id":"Casablanca","name":"Casablanca","wikipedia":"Casablanca"},
{"id":"Koulikoro","name":"Koulikoro","wikipedia":"Koulikoro"},
{"id":"Rabat","name":"Rabat","wikipedia":"Rabat"},
{"id":"Tórshavn","name":"Tórshavn","wikipedia":"Tórshavn"},
{"id":"Dublin","name":"Dublin","wikipedia":"Dublin"},
{"id":"Seville","name":"Seville","wikipedia":"Seville"},
{"id":"Belfast","name":"Belfast","wikipedia":"Belfast"},
{"id":"Jamestown","name":"Jamestown","wikipedia":"Jamestown,_Saint_Helena"},
{"id":"Gibraltar","name":"Gibraltar","wikipedia":"Gibraltar"},
{"id":"Yamoussoukro","name":"Yamoussoukro","wikipedia":"Yamoussoukro"},
{"id":"Douglas","name":"Douglas","wikipedia":"Douglas,_Isle_of_Man"},
{"id":"Málaga","name":"Málaga","wikipedia":"Málaga"},
{"id":"Glasgow","name":"Glasgow","wikipedia":"Glasgow"},
{"id":"Abidjan","name":"Abidjan","wikipedia":"Abidjan"},
{"id":"Madrid","name":"Madrid","wikipedia":"Madrid"},
{"id":"Cardiff","name":"Cardiff","wikipedia":"Cardiff"},
{"id":"Edinburgh","name":"Edinburgh","wikipedia":"Edinburgh"},
{"id":"Timbuktu","name":"Timbuktu","wikipedia":"Timbuktu"},
{"id":"Liverpool","name":"Liverpool","wikipedia":"Liverpool"},
{"id":"Bilbao","name":"Bilbao","wikipedia":"Bilbao"},
{"id":"Manchester","name":"Manchester","wikipedia":"Manchester"},
{"id":"Aberdeen","name":"Aberdeen","wikipedia":"Aberdeen"},
{"id":"Birmingham","name":"Birmingham","wikipedia":"Birmingham"},
{"id":"Leeds","name":"Leeds","wikipedia":"Leeds"},
{"id":"Nantes","name":"Nantes","wikipedia":"Nantes"},
{"id":"Ouagadougou","name":"Ouagadougou","wikipedia":"Ouagadougou"},
{"id":"Tamale","name":"Tamale","wikipedia":"Tamale,_Ghana"},
{"id":"Valencia","name":"Valencia","wikipedia":"Valencia,_Spain"},
{"id":"Accra","name":"Accra","wikipedia":"Accra"},
{"id":"London","name":"London","wikipedia":"London"},
{"id":"Greenwich","name":"Greenwich","wikipedia":"Greenwich"},
{"id":"Lomé","name":"Lomé","wikipedia":"Lomé"},
{"id":"Toulouse","name":"Toulouse","wikipedia":"Toulouse"},
{"id":"Andorra la Vella","name":"Andorra la Vella","wikipedia":"Andorra_la_Vella"},
{"id":"Ibiza","name":"Ibiza","wikipedia":"Ibiza"},
{"id":"Niamey","name":"Niamey","wikipedia":"Niamey"},
{"id":"Barcelona","name":"Barcelona","wikipedia":"Barcelona"},
{"id":"Paris","name":"Paris","wikipedia":"Paris"},
{"id":"Cotonou","name":"Cotonou","wikipedia":"Cotonou"},
{"id":"Porto-Novo","name":"Porto-Novo","wikipedia":"Porto-Novo"},
{"id":"Palma","name":"Palma","wikipedia":"Palma,_Majorca"},
{"id":"Algiers","name":"Algiers","wikipedia":"Algiers"},
{"id":"Lagos","name":"Lagos","wikipedia":"Lagos"},
{"id":"Ibadan","name":"Ibadan","wikipedia":"Ibadan"},
{"id":"The Hague","name":"The Hague","wikipedia":"The_Hague"},
{"id":"Brussels","name":"Brussels","wikipedia":"Brussels"},
{"id":"Antwerp","name":"Antwerp","wikipedia":"Antwerp"},
{"id":"Rotterdam","name":"Rotterdam","wikipedia":"Rotterdam"},
{"id":"Lyon","name":"Lyon","wikipedia":"Lyon"},
{"id":"Amsterdam","name":"Amsterdam","wikipedia":"Amsterdam"},
{"id":"Marseille","name":"Marseille","wikipedia":"Marseille"},
{"id":"Bergen","name":"Bergen","wikipedia":"Bergen"},
{"id":"Luxembourg (city)","name":"Luxembourg (city)","wikipedia":"Luxembourg_(city)"},
{"id":"Geneva","name":"Geneva","wikipedia":"Geneva"},
{"id":"São Tomé","name":"São Tomé","wikipedia":"São_Tomé"},
{"id":"Düsseldorf","name":"Düsseldorf","wikipedia":"Düsseldorf"},
{"id":"Cologne","name":"Cologne","wikipedia":"Cologne"},
{"id":"Cannes","name":"Cannes","wikipedia":"Cannes"},
{"id":"Nice","name":"Nice","wikipedia":"Nice"},
{"id":"Monaco","name":"Monaco","wikipedia":"Monaco"},
{"id":"Bern","name":"Bern","wikipedia":"Bern"},
{"id":"Abuja","name":"Abuja","wikipedia":"Abuja"},
{"id":"Enugu","name":"Enugu","wikipedia":"Enugu"},
{"id":"Turin","name":"Turin","wikipedia":"Turin"},
{"id":"Strasbourg","name":"Strasbourg","wikipedia":"Strasbourg"},
{"id":"Kano","name":"Kano","wikipedia":"Kano"},
{"id":"Zürich","name":"Zürich","wikipedia":"Zürich"},
{"id":"Frankfurt","name":"Frankfurt","wikipedia":"Frankfurt"},
{"id":"Malabo","name":"Malabo","wikipedia":"Malabo"},
{"id":"Stuttgart","name":"Stuttgart","wikipedia":"Stuttgart"},
{"id":"Milan","name":"Milan","wikipedia":"Milan"},
{"id":"Libreville","name":"Libreville","wikipedia":"Libreville"},
{"id":"Vaduz","name":"Vaduz","wikipedia":"Vaduz"},
{"id":"Douala","name":"Douala","wikipedia":"Douala"},
{"id":"Hanover","name":"Hanover","wikipedia":"Hanover"},
{"id":"Hamburg","name":"Hamburg","wikipedia":"Hamburg"},
{"id":"Tunis","name":"Tunis","wikipedia":"Tunis"},
{"id":"Aarhus","name":"Aarhus","wikipedia":"Aarhus"},
{"id":"Oslo","name":"Oslo","wikipedia":"Oslo"},
{"id":"Innsbruck","name":"Innsbruck","wikipedia":"Innsbruck"},
{"id":"Yaoundé","name":"Yaoundé","wikipedia":"Yaoundé"},
{"id":"Munich","name":"Munich","wikipedia":"Munich"},
{"id":"Gothenburg","name":"Gothenburg","wikipedia":"Gothenburg"},
{"id":"Leipzig","name":"Leipzig","wikipedia":"Leipzig"},
{"id":"City of San Marino","name":"City of San Marino","wikipedia":"City_of_San_Marino"},
{"id":"Vatican City","name":"Vatican City","wikipedia":"Vatican_City"},
{"id":"Rome","name":"Rome","wikipedia":"Rome"},
{"id":"Copenhagen","name":"Copenhagen","wikipedia":"Copenhagen"},
{"id":"Malmö","name":"Malmö","wikipedia":"Malmö"},
{"id":"Salzburg","name":"Salzburg","wikipedia":"Salzburg"},
{"id":"Tripoli","name":"Tripoli","wikipedia":"Tripoli"},
{"id":"Luanda","name":"Luanda","wikipedia":"Luanda"},
{"id":"Berlin","name":"Berlin","wikipedia":"Berlin"},
{"id":"Dresden","name":"Dresden","wikipedia":"Dresden"},
{"id":"Naples","name":"Naples","wikipedia":"Naples"},
{"id":"Linz","name":"Linz","wikipedia":"Linz"},
{"id":"Prague","name":"Prague","wikipedia":"Prague"},
{"id":"Sabha","name":"Sabha","wikipedia":"Sabha,_Libya"},
{"id":"Birkirkara","name":"Birkirkara","wikipedia":"Birkirkara"},
{"id":"Ljubljana","name":"Ljubljana","wikipedia":"Ljubljana"},
{"id":"Valletta","name":"Valletta","wikipedia":"Valletta"},
{"id":"N'Djamena","name":"N'Djamena","wikipedia":"N'Djamena"},
{"id":"Brazzaville","name":"Brazzaville","wikipedia":"Brazzaville"},
{"id":"Kinshasa","name":"Kinshasa","wikipedia":"Kinshasa"},
{"id":"Graz","name":"Graz","wikipedia":"Graz"},
{"id":"Longyearbyen","name":"Longyearbyen","wikipedia":"Longyearbyen"},
{"id":"Zagreb","name":"Zagreb","wikipedia":"Zagreb"},
{"id":"Vienna","name":"Vienna","wikipedia":"Vienna"},
{"id":"Split (city)","name":"Split (city)","wikipedia":"Split_(city)"},
{"id":"Bratislava","name":"Bratislava","wikipedia":"Bratislava"},
{"id":"Stockholm","name":"Stockholm","wikipedia":"Stockholm"},
{"id":"Sarajevo","name":"Sarajevo","wikipedia":"Sarajevo"},
{"id":"Cape Town","name":"Cape Town","wikipedia":"Cape_Town"},
{"id":"Bangui","name":"Bangui","wikipedia":"Bangui"},
{"id":"Gdańsk","name":"Gdańsk","wikipedia":"Gdańsk"},
{"id":"Budapest","name":"Budapest","wikipedia":"Budapest"},
{"id":"Podgorica","name":"Podgorica","wikipedia":"Podgorica"},
{"id":"Tirana","name":"Tirana","wikipedia":"Tirana"},
{"id":"Kraków","name":"Kraków","wikipedia":"Kraków"},
{"id":"Belgrade","name":"Belgrade","wikipedia":"Belgrade"},
{"id":"Kaliningrad","name":"Kaliningrad","wikipedia":"Kaliningrad"},
{"id":"Warsaw","name":"Warsaw","wikipedia":"Warsaw"},
{"id":"Pristina","name":"Pristina","wikipedia":"Pristina"},
{"id":"Skopje","name":"Skopje","wikipedia":"Skopje"},
{"id":"Thessaloniki","name":"Thessaloniki","wikipedia":"Thessaloniki"},
{"id":"Sofia","name":"Sofia","wikipedia":"Sofia"},
{"id":"Athens","name":"Athens","wikipedia":"Athens"},
{"id":"Tampere","name":"Tampere","wikipedia":"Tampere"},
{"id":"Lviv","name":"Lviv","wikipedia":"Lviv"},
{"id":"Riga","name":"Riga","wikipedia":"Riga"},
{"id":"Espoo","name":"Espoo","wikipedia":"Espoo"},
{"id":"Tallinn","name":"Tallinn","wikipedia":"Tallinn"},
{"id":"Helsinki","name":"Helsinki","wikipedia":"Helsinki"},
{"id":"Vilnius","name":"Vilnius","wikipedia":"Vilnius"},
{"id":"Port Elizabeth","name":"Port Elizabeth","wikipedia":"Port_Elizabeth"},
{"id":"Livingstone","name":"Livingstone","wikipedia":"Livingstone,_Zambia"},
{"id":"Gaborone","name":"Gaborone","wikipedia":"Gaborone"},
{"id":"Bucharest","name":"Bucharest","wikipedia":"Bucharest"},
{"id":"Bloemfontein","name":"Bloemfontein","wikipedia":"Bloemfontein"},
{"id":"Tartu","name":"Tartu","wikipedia":"Tartu"},
{"id":"İzmir","name":"İzmir","wikipedia":"İzmir"},
{"id":"Lubumbashi","name":"Lubumbashi","wikipedia":"Lubumbashi"},
{"id":"Maseru","name":"Maseru","wikipedia":"Maseru"},
{"id":"Francistown","name":"Francistown","wikipedia":"Francistown"},
{"id":"Minsk","name":"Minsk","wikipedia":"Minsk"},
{"id":"Johannesburg","name":"Johannesburg","wikipedia":"Johannesburg"},
{"id":"Pretoria","name":"Pretoria","wikipedia":"Pretoria"},
{"id":"Lusaka","name":"Lusaka","wikipedia":"Lusaka"},
{"id":"Ndola","name":"Ndola","wikipedia":"Ndola"},
{"id":"Bulawayo","name":"Bulawayo","wikipedia":"Bulawayo"},
{"id":"Chişinău","name":"Chişinău","wikipedia":"Chişinău"},
{"id":"Istanbul","name":"Istanbul","wikipedia":"Istanbul"},
{"id":"Bursa","name":"Bursa","wikipedia":"Bursa"},
{"id":"Bujumbura","name":"Bujumbura","wikipedia":"Bujumbura"},
{"id":"Tiraspol","name":"Tiraspol","wikipedia":"Tiraspol"},
{"id":"Alexandria","name":"Alexandria","wikipedia":"Alexandria"},
{"id":"Kigali","name":"Kigali","wikipedia":"Kigali"},
{"id":"Saint Petersburg","name":"Saint Petersburg","wikipedia":"Saint_Petersburg"},
{"id":"Kiev","name":"Kiev","wikipedia":"Kiev"},
{"id":"Odessa","name":"Odessa","wikipedia":"Odessa"},
{"id":"Harare","name":"Harare","wikipedia":"Harare"},
{"id":"Durban","name":"Durban","wikipedia":"Durban"},
{"id":"Mbabane","name":"Mbabane","wikipedia":"Mbabane"},
{"id":"Lobamba","name":"Lobamba","wikipedia":"Lobamba"},
{"id":"Cairo","name":"Cairo","wikipedia":"Cairo"},
{"id":"Manzini","name":"Manzini","wikipedia":"Manzini,_Swaziland"},
{"id":"Port Said","name":"Port Said","wikipedia":"Port_Said"},
{"id":"Konya","name":"Konya","wikipedia":"Konya"},
{"id":"Omdurman","name":"Omdurman","wikipedia":"Omdurman"},
{"id":"Khartoum","name":"Khartoum","wikipedia":"Khartoum"},
{"id":"Suez","name":"Suez","wikipedia":"Suez"},
{"id":"Maputo","name":"Maputo","wikipedia":"Maputo"},
{"id":"Luxor","name":"Luxor","wikipedia":"Luxor"},
{"id":"Ankara","name":"Ankara","wikipedia":"Ankara"},
{"id":"Mwanza","name":"Mwanza","wikipedia":"Mwanza"},
{"id":"Murmansk","name":"Murmansk","wikipedia":"Murmansk"},
{"id":"Nicosia","name":"Nicosia","wikipedia":"Nicosia"},
{"id":"Lilongwe","name":"Lilongwe","wikipedia":"Lilongwe"},
{"id":"Simferopol","name":"Simferopol","wikipedia":"Simferopol"},
{"id":"Gaza","name":"Gaza","wikipedia":"Gaza"},
{"id":"Mersin","name":"Mersin","wikipedia":"Mersin"},
{"id":"Tel Aviv","name":"Tel Aviv","wikipedia":"Tel_Aviv"},
{"id":"Blantyre","name":"Blantyre","wikipedia":"Blantyre,_Malawi"},
{"id":"Jerusalem","name":"Jerusalem","wikipedia":"Jerusalem"},
{"id":"Adana","name":"Adana","wikipedia":"Adana"},
{"id":"Beirut","name":"Beirut","wikipedia":"Beirut"},
{"id":"Dodoma","name":"Dodoma","wikipedia":"Dodoma"},
{"id":"Amman","name":"Amman","wikipedia":"Amman"},
{"id":"Damascus","name":"Damascus","wikipedia":"Damascus"},
{"id":"Kharkiv","name":"Kharkiv","wikipedia":"Kharkiv"},
{"id":"Nairobi","name":"Nairobi","wikipedia":"Nairobi"},
{"id":"Gaziantep","name":"Gaziantep","wikipedia":"Gaziantep"},
{"id":"Moscow","name":"Moscow","wikipedia":"Moscow"},
{"id":"Addis Ababa","name":"Addis Ababa","wikipedia":"Addis_Ababa"},
{"id":"Asmara","name":"Asmara","wikipedia":"Asmara"},
{"id":"Jeddah","name":"Jeddah","wikipedia":"Jeddah"},
{"id":"Zanzibar City","name":"Zanzibar City","wikipedia":"Zanzibar_City"},
{"id":"Dar es Salaam","name":"Dar es Salaam","wikipedia":"Dar_es_Salaam"},
{"id":"Medina","name":"Medina","wikipedia":"Medina"},
{"id":"Mecca","name":"Mecca","wikipedia":"Mecca"},
{"id":"Sukhumi","name":"Sukhumi","wikipedia":"Sukhumi"},
{"id":"Djibouti (city)","name":"Djibouti (city)","wikipedia":"Djibouti_(city)"},
{"id":"Moroni","name":"Moroni","wikipedia":"Moroni,_Comoros"},
{"id":"Tskhinvali","name":"Tskhinvali","wikipedia":"Tskhinvali"},
{"id":"Sana'a","name":"Sana'a","wikipedia":"Sana'a"},
{"id":"Baghdad","name":"Baghdad","wikipedia":"Baghdad"},
{"id":"Nizhny Novgorod","name":"Nizhny Novgorod","wikipedia":"Nizhny_Novgorod"},
{"id":"Hargeisa","name":"Hargeisa","wikipedia":"Hargeisa"},
{"id":"Arbil","name":"Arbil","wikipedia":"Arbil"},
{"id":"Yerevan","name":"Yerevan","wikipedia":"Yerevan"},
{"id":"Tbilisi","name":"Tbilisi","wikipedia":"Tbilisi"},
{"id":"Mamoudzou","name":"Mamoudzou","wikipedia":"Mamoudzou"},
{"id":"Mogadishu","name":"Mogadishu","wikipedia":"Mogadishu"},
{"id":"Tabriz","name":"Tabriz","wikipedia":"Tabriz"},
{"id":"Riyadh","name":"Riyadh","wikipedia":"Riyadh"},
{"id":"Stepanakert","name":"Stepanakert","wikipedia":"Stepanakert"},
{"id":"Antananarivo","name":"Antananarivo","wikipedia":"Antananarivo"},
{"id":"Basra","name":"Basra","wikipedia":"Basra"},
{"id":"Kuwait City","name":"Kuwait City","wikipedia":"Kuwait_City"},
{"id":"Baku","name":"Baku","wikipedia":"Baku"},
{"id":"Dammam","name":"Dammam","wikipedia":"Dammam"},
{"id":"Samara","name":"Samara","wikipedia":"Samara,_Russia"},
{"id":"Manama","name":"Manama","wikipedia":"Manama"},
{"id":"Tehran","name":"Tehran","wikipedia":"Tehran"},
{"id":"Doha","name":"Doha","wikipedia":"Doha"},
{"id":"Abu Dhabi","name":"Abu Dhabi","wikipedia":"Abu_Dhabi"},
{"id":"Dubai","name":"Dubai","wikipedia":"Dubai"},
{"id":"Victoria","name":"Victoria","wikipedia":"Victoria,_Seychelles"},
{"id":"Saint-Denis","name":"Saint-Denis","wikipedia":"Saint-Denis,_Réunion"},
{"id":"Perm","name":"Perm","wikipedia":"Perm"},
{"id":"Port Louis","name":"Port Louis","wikipedia":"Port_Louis"},
{"id":"Ashgabat","name":"Ashgabat","wikipedia":"Ashgabat"},
{"id":"Muscat","name":"Muscat","wikipedia":"Muscat,_Oman"},
{"id":"Nukus","name":"Nukus","wikipedia":"Nukus"},
{"id":"Mashhad","name":"Mashhad","wikipedia":"Mashhad"},
{"id":"Yekaterinburg","name":"Yekaterinburg","wikipedia":"Yekaterinburg"},
{"id":"Kandahar","name":"Kandahar","wikipedia":"Kandahar"},
{"id":"Karachi","name":"Karachi","wikipedia":"Karachi"},
{"id":"Hyderabad","name":"Hyderabad","wikipedia":"Hyderabad,_Andhra_Pradesh"},
{"id":"Dushanbe","name":"Dushanbe","wikipedia":"Dushanbe"},
{"id":"Kabul","name":"Kabul","wikipedia":"Kabul"},
{"id":"Tashkent","name":"Tashkent","wikipedia":"Tashkent"},
{"id":"Astana","name":"Astana","wikipedia":"Astana"},
{"id":"Multan","name":"Multan","wikipedia":"Multan"},
{"id":"Peshawar","name":"Peshawar","wikipedia":"Peshawar"},
{"id":"Namangan","name":"Namangan","wikipedia":"Namangan"},
{"id":"Ahmedabad","name":"Ahmedabad","wikipedia":"Ahmedabad"},
{"id":"Mumbai","name":"Mumbai","wikipedia":"Mumbai"},
{"id":"Surat","name":"Surat","wikipedia":"Surat,_Gujarat"},
{"id":"Faisalabad","name":"Faisalabad","wikipedia":"Faisalabad"},
{"id":"Rawalpindi","name":"Rawalpindi","wikipedia":"Rawalpindi"},
{"id":"Islamabad","name":"Islamabad","wikipedia":"Islamabad"},
{"id":"Omsk","name":"Omsk","wikipedia":"Omsk"},
{"id":"Malé","name":"Malé","wikipedia":"Malé"},
{"id":"Pune","name":"Pune","wikipedia":"Pune"},
{"id":"Lahore","name":"Lahore","wikipedia":"Lahore"},
{"id":"Bishkek","name":"Bishkek","wikipedia":"Bishkek"},
{"id":"Srinagar","name":"Srinagar","wikipedia":"Srinagar"},
{"id":"Amritsar","name":"Amritsar","wikipedia":"Amritsar"},
{"id":"Jaipur","name":"Jaipur","wikipedia":"Jaipur"},
{"id":"Ludhiana","name":"Ludhiana","wikipedia":"Ludhiana"},
{"id":"Almaty","name":"Almaty","wikipedia":"Almaty"},
{"id":"New Delhi","name":"New Delhi","wikipedia":"New_Delhi"},
{"id":"Bangalore","name":"Bangalore","wikipedia":"Bangalore"},
{"id":"Nagpur","name":"Nagpur","wikipedia":"Nagpur"},
{"id":"Colombo","name":"Colombo","wikipedia":"Colombo"},
{"id":"Sri Jayawardenapura-Kotte","name":"Sri Jayawardenapura-Kotte","wikipedia":"Sri_Jayawardenapura-Kotte"},
{"id":"Chennai","name":"Chennai","wikipedia":"Chennai"},
{"id":"Kanpur","name":"Kanpur","wikipedia":"Kanpur"},
{"id":"Kandy","name":"Kandy","wikipedia":"Kandy"},
{"id":"Lucknow","name":"Lucknow","wikipedia":"Lucknow"},
{"id":"Batticaloa","name":"Batticaloa","wikipedia":"Batticaloa"},
{"id":"Novosibirsk","name":"Novosibirsk","wikipedia":"Novosibirsk"},
{"id":"Patna","name":"Patna","wikipedia":"Patna"},
{"id":"Kathmandu","name":"Kathmandu","wikipedia":"Kathmandu"},
{"id":"Ürümqi","name":"Ürümqi","wikipedia":"Ürümqi"},
{"id":"Norilsk","name":"Norilsk","wikipedia":"Norilsk"},
{"id":"Kolkata","name":"Kolkata","wikipedia":"Kolkata"},
{"id":"Gangtok","name":"Gangtok","wikipedia":"Gangtok"},
{"id":"Shigatse","name":"Shigatse","wikipedia":"Shigatse"},
{"id":"Thimphu","name":"Thimphu","wikipedia":"Thimphu"},
{"id":"Dhaka","name":"Dhaka","wikipedia":"Dhaka"},
{"id":"Lhasa","name":"Lhasa","wikipedia":"Lhasa"},
{"id":"Agartala","name":"Agartala","wikipedia":"Agartala"},
{"id":"Guwahati","name":"Guwahati","wikipedia":"Guwahati"},
{"id":"Chittagong","name":"Chittagong","wikipedia":"Chittagong"},
{"id":"Shillong","name":"Shillong","wikipedia":"Shillong"},
{"id":"Port Blair","name":"Port Blair","wikipedia":"Port_Blair"},
{"id":"Dibrugarh","name":"Dibrugarh","wikipedia":"Dibrugarh"},
{"id":"Banda Aceh","name":"Banda Aceh","wikipedia":"Banda_Aceh"},
{"id":"Naypyidaw","name":"Naypyidaw","wikipedia":"Naypyidaw"},
{"id":"Yangon","name":"Yangon","wikipedia":"Yangon"},
{"id":"Medan","name":"Medan","wikipedia":"Medan"},
{"id":"Phuket (city)","name":"Phuket (city)","wikipedia":"Phuket_(city)"},
{"id":"Chiang Mai","name":"Chiang Mai","wikipedia":"Chiang_Mai"},
{"id":"Surat Thani","name":"Surat Thani","wikipedia":"Surat_Thani"},
{"id":"Padang","name":"Padang","wikipedia":"Padang,_Indonesia"},
{"id":"Alor Star","name":"Alor Star","wikipedia":"Alor_Star"},
{"id":"Hat Yai","name":"Hat Yai","wikipedia":"Hat_Yai"},
{"id":"Bangkok","name":"Bangkok","wikipedia":"Bangkok"},
{"id":"Pattaya","name":"Pattaya","wikipedia":"Pattaya"},
{"id":"Ipoh","name":"Ipoh","wikipedia":"Ipoh"},
{"id":"Pekanbaru","name":"Pekanbaru","wikipedia":"Pekanbaru"},
{"id":"Bratsk","name":"Bratsk","wikipedia":"Bratsk"},
{"id":"Kuala Lumpur","name":"Kuala Lumpur","wikipedia":"Kuala_Lumpur"},
{"id":"Xining","name":"Xining","wikipedia":"Xining"},
{"id":"Nakhon Ratchasima","name":"Nakhon Ratchasima","wikipedia":"Nakhon_Ratchasima"},
{"id":"Kota Bharu","name":"Kota Bharu","wikipedia":"Kota_Bharu"},
{"id":"Malacca Town","name":"Malacca Town","wikipedia":"Malacca_Town"},
{"id":"Vientiane","name":"Vientiane","wikipedia":"Vientiane"},
{"id":"Kunming","name":"Kunming","wikipedia":"Kunming"},
{"id":"Udon Thani","name":"Udon Thani","wikipedia":"Udon_Thani"},
{"id":"Johor Bahru","name":"Johor Bahru","wikipedia":"Johor_Bahru"},
{"id":"Lanzhou","name":"Lanzhou","wikipedia":"Lanzhou"},
{"id":"Singapore","name":"Singapore","wikipedia":"Singapore"},
{"id":"Siem Reap","name":"Siem Reap","wikipedia":"Siem_Reap"},
{"id":"Chengdu","name":"Chengdu","wikipedia":"Chengdu"},
{"id":"Palembang","name":"Palembang","wikipedia":"Palembang"},
{"id":"Phnom Penh","name":"Phnom Penh","wikipedia":"Phnom_Penh"},
{"id":"Hanoi","name":"Hanoi","wikipedia":"Hanoi"},
{"id":"Chongqing","name":"Chongqing","wikipedia":"Chongqing"},
{"id":"Hai Phong","name":"Hai Phong","wikipedia":"Hai_Phong"},
{"id":"Ho Chi Minh City","name":"Ho Chi Minh City","wikipedia":"Ho_Chi_Minh_City"},
{"id":"Jakarta","name":"Jakarta","wikipedia":"Jakarta"},
{"id":"Bogor","name":"Bogor","wikipedia":"Bogor"},
{"id":"Ulan Bator","name":"Ulan Bator","wikipedia":"Ulan_Bator"},
{"id":"Bandung","name":"Bandung","wikipedia":"Bandung"},
{"id":"Huế","name":"Huế","wikipedia":"Huế"},
{"id":"Da Nang","name":"Da Nang","wikipedia":"Da_Nang"},
{"id":"Nanning","name":"Nanning","wikipedia":"Nanning"},
{"id":"Xi'an","name":"Xi'an","wikipedia":"Xi'an"},
{"id":"Pontianak","name":"Pontianak","wikipedia":"Pontianak,_Indonesia"},
{"id":"Kuching","name":"Kuching","wikipedia":"Kuching"},
{"id":"Yogyakarta (city)","name":"Yogyakarta (city)","wikipedia":"Yogyakarta_(city)"},
{"id":"Semarang","name":"Semarang","wikipedia":"Semarang"},
{"id":"Taiyuan","name":"Taiyuan","wikipedia":"Taiyuan"},
{"id":"Malang","name":"Malang","wikipedia":"Malang"},
{"id":"Surabaya","name":"Surabaya","wikipedia":"Surabaya"},
{"id":"Guangzhou","name":"Guangzhou","wikipedia":"Guangzhou"},
{"id":"Macau","name":"Macau","wikipedia":"Macau"},
{"id":"Zhengzhou","name":"Zhengzhou","wikipedia":"Zhengzhou"},
{"id":"Dongguan","name":"Dongguan","wikipedia":"Dongguan"},
{"id":"Miri","name":"Miri","wikipedia":"Miri"},
{"id":"Shenzhen","name":"Shenzhen","wikipedia":"Shenzhen"},
{"id":"Hong Kong","name":"Hong Kong","wikipedia":"Hong Kong"},
{"id":"Wuhan","name":"Wuhan","wikipedia":"Wuhan"},
{"id":"Handan","name":"Handan","wikipedia":"Handan"},
{"id":"Shijiazhuang","name":"Shijiazhuang","wikipedia":"Shijiazhuang"},
{"id":"Bandar Seri Begawan","name":"Bandar Seri Begawan","wikipedia":"Bandar_Seri_Begawan"},
{"id":"Denpasar","name":"Denpasar","wikipedia":"Denpasar"},
{"id":"Mandurah","name":"Mandurah","wikipedia":"Mandurah"},
{"id":"Perth","name":"Perth","wikipedia":"Perth,_Western_Australia"},
{"id":"Kota Kinabalu","name":"Kota Kinabalu","wikipedia":"Kota_Kinabalu"},
{"id":"Beijing","name":"Beijing","wikipedia":"Beijing"},
{"id":"Balikpapan","name":"Balikpapan","wikipedia":"Balikpapan"},
{"id":"Jinan","name":"Jinan","wikipedia":"Jinan"},
{"id":"Tianjin","name":"Tianjin","wikipedia":"Tianjin"},
{"id":"Port Hedland","name":"Port Hedland","wikipedia":"Port_Hedland,_Western_Australia"},
{"id":"Nanjing","name":"Nanjing","wikipedia":"Nanjing"},
{"id":"Makassar","name":"Makassar","wikipedia":"Makassar"},
{"id":"Hangzhou","name":"Hangzhou","wikipedia":"Hangzhou"},
{"id":"Kaohsiung","name":"Kaohsiung","wikipedia":"Kaohsiung"},
{"id":"Qingdao","name":"Qingdao","wikipedia":"Qingdao"},
{"id":"Taichung","name":"Taichung","wikipedia":"Taichung"},
{"id":"Manila","name":"Manila","wikipedia":"Manila"},
{"id":"Quezon City","name":"Quezon City","wikipedia":"Quezon_City"},
{"id":"Makati City","name":"Makati City","wikipedia":"Makati_City"},
{"id":"Shanghai","name":"Shanghai","wikipedia":"Shanghai"},
{"id":"Taipei","name":"Taipei","wikipedia":"Taipei"},
{"id":"Dalian","name":"Dalian","wikipedia":"Dalian"},
{"id":"Iloilo City","name":"Iloilo City","wikipedia":"Iloilo_City"},
{"id":"Zamboanga City","name":"Zamboanga City","wikipedia":"Zamboanga_City"},
{"id":"Shenyang","name":"Shenyang","wikipedia":"Shenyang"},
{"id":"Tagbilaran","name":"Tagbilaran","wikipedia":"Tagbilaran"},
{"id":"Cebu City","name":"Cebu City","wikipedia":"Cebu_City"},
{"id":"Changchun","name":"Changchun","wikipedia":"Changchun"},
{"id":"Dili","name":"Dili","wikipedia":"Dili"},
{"id":"Pyongyang","name":"Pyongyang","wikipedia":"Pyongyang"},
{"id":"Davao City","name":"Davao City","wikipedia":"Davao_City"},
{"id":"Kaesong","name":"Kaesong","wikipedia":"Kaesong"},
{"id":"Harbin","name":"Harbin","wikipedia":"Harbin"},
{"id":"Incheon","name":"Incheon","wikipedia":"Incheon"},
{"id":"Seoul","name":"Seoul","wikipedia":"Seoul"},
{"id":"Wonsan","name":"Wonsan","wikipedia":"Wonsan"},
{"id":"Okinawa","name":"Okinawa","wikipedia":"Okinawa,_Okinawa"},
{"id":"Ambon","name":"Ambon","wikipedia":"Ambon,_Maluku"},
{"id":"Daegu","name":"Daegu","wikipedia":"Daegu"},
{"id":"Busan","name":"Busan","wikipedia":"Busan"},
{"id":"Yakutsk","name":"Yakutsk","wikipedia":"Yakutsk"},
{"id":"Chongjin","name":"Chongjin","wikipedia":"Chongjin"},
{"id":"Fukuoka","name":"Fukuoka","wikipedia":"Fukuoka"},
{"id":"Darwin","name":"Darwin","wikipedia":"Darwin,_Northern_Territory"},
{"id":"Vladivostok","name":"Vladivostok","wikipedia":"Vladivostok"},
{"id":"Hiroshima","name":"Hiroshima","wikipedia":"Hiroshima"},
{"id":"Koror","name":"Koror","wikipedia":"Koror"},
{"id":"Melekeok","name":"Melekeok","wikipedia":"Melekeok"},
{"id":"Kobe","name":"Kobe","wikipedia":"Kobe"},
{"id":"Osaka","name":"Osaka","wikipedia":"Osaka"},
{"id":"Kyoto","name":"Kyoto","wikipedia":"Kyoto"},
{"id":"Nagoya","name":"Nagoya","wikipedia":"Nagoya"},
{"id":"Adelaide","name":"Adelaide","wikipedia":"Adelaide"},
{"id":"Yokohama","name":"Yokohama","wikipedia":"Yokohama"},
{"id":"Kawasaki","name":"Kawasaki","wikipedia":"Kawasaki,_Kanagawa"},
{"id":"Tokyo","name":"Tokyo","wikipedia":"Tokyo"},
{"id":"Jayapura","name":"Jayapura","wikipedia":"Jayapura"},
{"id":"Sapporo","name":"Sapporo","wikipedia":"Sapporo"},
{"id":"Geelong","name":"Geelong","wikipedia":"Geelong"},
{"id":"Hagåtña","name":"Hagåtña","wikipedia":"Hagåtña,_Guam"},
{"id":"Dededo","name":"Dededo","wikipedia":"Dededo,_Guam"},
{"id":"Melbourne","name":"Melbourne","wikipedia":"Melbourne"},
{"id":"Saipan","name":"Saipan","wikipedia":"Saipan"},
{"id":"Cairns","name":"Cairns","wikipedia":"Cairns"},
{"id":"Townsville","name":"Townsville","wikipedia":"Townsville"},
{"id":"Port Moresby","name":"Port Moresby","wikipedia":"Port_Moresby"},
{"id":"Hobart","name":"Hobart","wikipedia":"Hobart"},
{"id":"Canberra","name":"Canberra","wikipedia":"Canberra"},
{"id":"Rockhampton","name":"Rockhampton","wikipedia":"Rockhampton"},
{"id":"Magadan","name":"Magadan","wikipedia":"Magadan"},
{"id":"Wollongong","name":"Wollongong","wikipedia":"Wollongong"},
{"id":"Sydney","name":"Sydney","wikipedia":"Sydney"},
{"id":"Newcastle","name":"Newcastle","wikipedia":"Newcastle,_New_South_Wales"},
{"id":"Weno","name":"Weno","wikipedia":"Weno"},
{"id":"Brisbane","name":"Brisbane","wikipedia":"Brisbane"},
{"id":"Gold Coast","name":"Gold Coast","wikipedia":"Gold_Coast,_Queensland"},
{"id":"Palikir","name":"Palikir","wikipedia":"Palikir"},
{"id":"Petropavlovsk-Kamchatsky","name":"Petropavlovsk-Kamchatsky","wikipedia":"Petropavlovsk-Kamchatsky"},
{"id":"Honiara","name":"Honiara","wikipedia":"Honiara"},
{"id":"Nouméa","name":"Nouméa","wikipedia":"Nouméa"},
{"id":"Yaren District","name":"Yaren District","wikipedia":"Yaren_District"},
{"id":"Port Vila","name":"Port Vila","wikipedia":"Port_Vila"},
{"id":"Invercargill","name":"Invercargill","wikipedia":"Invercargill"},
{"id":"Dunedin","name":"Dunedin","wikipedia":"Dunedin"},
{"id":"Majuro","name":"Majuro","wikipedia":"Majuro"},
{"id":"Christchurch","name":"Christchurch","wikipedia":"Christchurch"},
{"id":"South Tarawa","name":"South Tarawa","wikipedia":"South_Tarawa"},
{"id":"Wellington","name":"Wellington","wikipedia":"Wellington"},
{"id":"Auckland","name":"Auckland","wikipedia":"Auckland"},
{"id":"Mata-Utu","name":"Mata-Utu","wikipedia":"Mata-Utu"},
{"id":"Anadyr (town)","name":"Anadyr (town)","wikipedia":"Anadyr_(town)"},
{"id":"Suva","name":"Suva","wikipedia":"Suva"},
{"id":"Funafuti","name":"Funafuti","wikipedia":"Funafuti"},
{"id":"Labasa","name":"Labasa","wikipedia":"Labasa"},
{"id":"Nukulaelae","name":"Nukulaelae","wikipedia":"Nukulaelae"}];